# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Smart_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(923, 470)
        self.TitleBar = QtWidgets.QWidget(Form)
        self.TitleBar.setGeometry(QtCore.QRect(0, 0, 901, 41))
        self.TitleBar.setMinimumSize(QtCore.QSize(0, 41))
        self.TitleBar.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        self.TitleBar.setFont(font)
        self.TitleBar.setMouseTracking(True)
        self.TitleBar.setStyleSheet("#TitleBar\n"
"{\n"
"    background-color:rgb(84, 84, 84)\n"
"}")
        self.TitleBar.setObjectName("TitleBar")
        self.layoutWidget = QtWidgets.QWidget(self.TitleBar)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 879, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleIcon = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleIcon.sizePolicy().hasHeightForWidth())
        self.TitleIcon.setSizePolicy(sizePolicy)
        self.TitleIcon.setMinimumSize(QtCore.QSize(25, 25))
        self.TitleIcon.setMaximumSize(QtCore.QSize(30, 30))
        self.TitleIcon.setAutoFillBackground(False)
        self.TitleIcon.setStyleSheet("border-image: url(D:/SmartImages/title_icon.ico);")
        self.TitleIcon.setText("")
        self.TitleIcon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TitleIcon.setObjectName("TitleIcon")
        self.horizontalLayout.addWidget(self.TitleIcon)
        self.TitleName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleName.sizePolicy().hasHeightForWidth())
        self.TitleName.setSizePolicy(sizePolicy)
        self.TitleName.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TitleName.setFont(font)
        self.TitleName.setMouseTracking(True)
        self.TitleName.setTabletTracking(False)
        self.TitleName.setStyleSheet("\n"
"font: 10pt \"微软雅黑\";\n"
"color:rgb(222, 222, 222)")
        self.TitleName.setObjectName("TitleName")
        self.horizontalLayout.addWidget(self.TitleName)
        spacerItem = QtWidgets.QSpacerItem(698, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.MinimizeButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinimizeButton.sizePolicy().hasHeightForWidth())
        self.MinimizeButton.setSizePolicy(sizePolicy)
        self.MinimizeButton.setMinimumSize(QtCore.QSize(0, 0))
        self.MinimizeButton.setMaximumSize(QtCore.QSize(25, 25))
        self.MinimizeButton.setStyleSheet("QPushButton{\n"
"            border-image: url(D:/SmartImages/minimize_first.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"            border-image: url(D:/SmartImages/minimize_latter.png);\n"
"}\n"
"")
        self.MinimizeButton.setText("")
        self.MinimizeButton.setObjectName("MinimizeButton")
        self.horizontalLayout.addWidget(self.MinimizeButton)
        self.CloseButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setMinimumSize(QtCore.QSize(0, 0))
        self.CloseButton.setMaximumSize(QtCore.QSize(25, 25))
        self.CloseButton.setStyleSheet("QPushButton{\n"
"            border-image: url(D:/SmartImages/close_first.png);\n"
"            hight:15pt;\n"
"            weight:15pt\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"            border-image: url(D:/SmartImages/close_latter.png);\n"
"}\n"
"")
        self.CloseButton.setText("")
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout.addWidget(self.CloseButton)
        self.MainBackgroud = QtWidgets.QWidget(Form)
        self.MainBackgroud.setGeometry(QtCore.QRect(0, 40, 901, 401))
        self.MainBackgroud.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MainBackgroud.setMouseTracking(True)
        self.MainBackgroud.setStyleSheet("#MainBackgroud\n"
"{\n"
"    background-color: rgb(62, 62, 62);\n"
"}")
        self.MainBackgroud.setObjectName("MainBackgroud")
        self.layoutWidget1 = QtWidgets.QWidget(self.MainBackgroud)
        self.layoutWidget1.setGeometry(QtCore.QRect(470, 3, 403, 371))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.state_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.state_3.setMinimumSize(QtCore.QSize(81, 30))
        self.state_3.setMaximumSize(QtCore.QSize(81, 30))
        self.state_3.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.state_3.setObjectName("state_3")
        self.horizontalLayout_9.addWidget(self.state_3)
        self.years = QtWidgets.QComboBox(self.layoutWidget1)
        self.years.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.years.sizePolicy().hasHeightForWidth())
        self.years.setSizePolicy(sizePolicy)
        self.years.setMinimumSize(QtCore.QSize(0, 0))
        self.years.setMaximumSize(QtCore.QSize(93, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.years.setFont(font)
        self.years.setObjectName("years")
        self.years.addItem("")
        self.years.addItem("")
        self.years.addItem("")
        self.horizontalLayout_9.addWidget(self.years)
        self.times_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.times_4.setMinimumSize(QtCore.QSize(0, 0))
        self.times_4.setMaximumSize(QtCore.QSize(81, 30))
        self.times_4.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.times_4.setObjectName("times_4")
        self.horizontalLayout_9.addWidget(self.times_4)
        self.months = QtWidgets.QComboBox(self.layoutWidget1)
        self.months.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.months.sizePolicy().hasHeightForWidth())
        self.months.setSizePolicy(sizePolicy)
        self.months.setMinimumSize(QtCore.QSize(0, 0))
        self.months.setMaximumSize(QtCore.QSize(93, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.months.setFont(font)
        self.months.setObjectName("months")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.months.addItem("")
        self.horizontalLayout_9.addWidget(self.months)
        self.times_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.times_2.setMinimumSize(QtCore.QSize(0, 0))
        self.times_2.setMaximumSize(QtCore.QSize(81, 30))
        self.times_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.times_2.setObjectName("times_2")
        self.horizontalLayout_9.addWidget(self.times_2)
        self.days = QtWidgets.QComboBox(self.layoutWidget1)
        self.days.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.days.sizePolicy().hasHeightForWidth())
        self.days.setSizePolicy(sizePolicy)
        self.days.setMinimumSize(QtCore.QSize(0, 0))
        self.days.setMaximumSize(QtCore.QSize(93, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.days.setFont(font)
        self.days.setObjectName("days")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.horizontalLayout_9.addWidget(self.days)
        self.times_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.times_3.setMinimumSize(QtCore.QSize(0, 0))
        self.times_3.setMaximumSize(QtCore.QSize(81, 30))
        self.times_3.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.times_3.setObjectName("times_3")
        self.horizontalLayout_9.addWidget(self.times_3)
        self.Analysisbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.Analysisbutton.setMinimumSize(QtCore.QSize(45, 23))
        self.Analysisbutton.setMaximumSize(QtCore.QSize(70, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Analysisbutton.setFont(font)
        self.Analysisbutton.setStyleSheet("")
        self.Analysisbutton.setCheckable(False)
        self.Analysisbutton.setChecked(False)
        self.Analysisbutton.setObjectName("Analysisbutton")
        self.horizontalLayout_9.addWidget(self.Analysisbutton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.show_data = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.show_data.setMinimumSize(QtCore.QSize(401, 331))
        self.show_data.setMaximumSize(QtCore.QSize(401, 360))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.show_data.setFont(font)
        self.show_data.setObjectName("show_data")
        self.verticalLayout_9.addWidget(self.show_data)
        self.layoutWidget2 = QtWidgets.QWidget(self.MainBackgroud)
        self.layoutWidget2.setGeometry(QtCore.QRect(14, 4, 436, 371))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.temp = QtWidgets.QLabel(self.layoutWidget2)
        self.temp.setMinimumSize(QtCore.QSize(81, 30))
        self.temp.setMaximumSize(QtCore.QSize(81, 30))
        self.temp.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.temp.setObjectName("temp")
        self.verticalLayout_4.addWidget(self.temp)
        self.light = QtWidgets.QLabel(self.layoutWidget2)
        self.light.setMinimumSize(QtCore.QSize(81, 30))
        self.light.setMaximumSize(QtCore.QSize(81, 30))
        self.light.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.light.setObjectName("light")
        self.verticalLayout_4.addWidget(self.light)
        self.state = QtWidgets.QLabel(self.layoutWidget2)
        self.state.setMinimumSize(QtCore.QSize(81, 30))
        self.state.setMaximumSize(QtCore.QSize(81, 30))
        self.state.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.state.setObjectName("state")
        self.verticalLayout_4.addWidget(self.state)
        self.state_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.state_2.setMinimumSize(QtCore.QSize(81, 30))
        self.state_2.setMaximumSize(QtCore.QSize(81, 30))
        self.state_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.state_2.setObjectName("state_2")
        self.verticalLayout_4.addWidget(self.state_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.show_temp = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.show_temp.setMinimumSize(QtCore.QSize(93, 29))
        self.show_temp.setMaximumSize(QtCore.QSize(93, 29))
        self.show_temp.setObjectName("show_temp")
        self.verticalLayout_3.addWidget(self.show_temp)
        self.show_light = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.show_light.setMinimumSize(QtCore.QSize(93, 29))
        self.show_light.setMaximumSize(QtCore.QSize(93, 29))
        self.show_light.setObjectName("show_light")
        self.verticalLayout_3.addWidget(self.show_light)
        self.show_state = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.show_state.setMinimumSize(QtCore.QSize(93, 30))
        self.show_state.setMaximumSize(QtCore.QSize(93, 35))
        self.show_state.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.show_state.setObjectName("show_state")
        self.verticalLayout_3.addWidget(self.show_state)
        self.show_state_2 = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.show_state_2.setMinimumSize(QtCore.QSize(93, 30))
        self.show_state_2.setMaximumSize(QtCore.QSize(93, 35))
        self.show_state_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.show_state_2.setObjectName("show_state_2")
        self.verticalLayout_3.addWidget(self.show_state_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SerialCOMLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.SerialCOMLabel.setMinimumSize(QtCore.QSize(62, 20))
        self.SerialCOMLabel.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SerialCOMLabel.setFont(font)
        self.SerialCOMLabel.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color:rgb(255, 255, 255)")
        self.SerialCOMLabel.setObjectName("SerialCOMLabel")
        self.verticalLayout.addWidget(self.SerialCOMLabel)
        self.SerialBaudRateLabel = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SerialBaudRateLabel.sizePolicy().hasHeightForWidth())
        self.SerialBaudRateLabel.setSizePolicy(sizePolicy)
        self.SerialBaudRateLabel.setMaximumSize(QtCore.QSize(81, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SerialBaudRateLabel.setFont(font)
        self.SerialBaudRateLabel.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color:rgb(255, 255, 255)")
        self.SerialBaudRateLabel.setObjectName("SerialBaudRateLabel")
        self.verticalLayout.addWidget(self.SerialBaudRateLabel)
        self.OpenLabel = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenLabel.sizePolicy().hasHeightForWidth())
        self.OpenLabel.setSizePolicy(sizePolicy)
        self.OpenLabel.setMaximumSize(QtCore.QSize(81, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.OpenLabel.setFont(font)
        self.OpenLabel.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color:rgb(255, 255, 255)")
        self.OpenLabel.setObjectName("OpenLabel")
        self.verticalLayout.addWidget(self.OpenLabel)
        self.temp_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.temp_2.setMinimumSize(QtCore.QSize(81, 24))
        self.temp_2.setMaximumSize(QtCore.QSize(200, 24))
        self.temp_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.temp_2.setObjectName("temp_2")
        self.verticalLayout.addWidget(self.temp_2)
        self.send_orders_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.send_orders_2.setMinimumSize(QtCore.QSize(81, 24))
        self.send_orders_2.setMaximumSize(QtCore.QSize(200, 24))
        self.send_orders_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.send_orders_2.setObjectName("send_orders_2")
        self.verticalLayout.addWidget(self.send_orders_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SerialCOMComboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.SerialCOMComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SerialCOMComboBox.sizePolicy().hasHeightForWidth())
        self.SerialCOMComboBox.setSizePolicy(sizePolicy)
        self.SerialCOMComboBox.setMinimumSize(QtCore.QSize(93, 29))
        self.SerialCOMComboBox.setMaximumSize(QtCore.QSize(93, 23))
        self.SerialCOMComboBox.setCurrentText("")
        self.SerialCOMComboBox.setObjectName("SerialCOMComboBox")
        self.verticalLayout_2.addWidget(self.SerialCOMComboBox)
        self.SerialBaudRateComboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.SerialBaudRateComboBox.setMinimumSize(QtCore.QSize(93, 29))
        self.SerialBaudRateComboBox.setMaximumSize(QtCore.QSize(93, 23))
        self.SerialBaudRateComboBox.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.SerialBaudRateComboBox.setEditable(False)
        self.SerialBaudRateComboBox.setObjectName("SerialBaudRateComboBox")
        self.SerialBaudRateComboBox.addItem("")
        self.SerialBaudRateComboBox.addItem("")
        self.SerialBaudRateComboBox.addItem("")
        self.SerialBaudRateComboBox.addItem("")
        self.SerialBaudRateComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.SerialBaudRateComboBox)
        self.OpenButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.OpenButton.setMinimumSize(QtCore.QSize(93, 29))
        self.OpenButton.setMaximumSize(QtCore.QSize(93, 23))
        self.OpenButton.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.OpenButton.setObjectName("OpenButton")
        self.verticalLayout_2.addWidget(self.OpenButton)
        self.change = QtWidgets.QPushButton(self.layoutWidget2)
        self.change.setMinimumSize(QtCore.QSize(93, 29))
        self.change.setMaximumSize(QtCore.QSize(93, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.change.setFont(font)
        self.change.setStyleSheet("")
        self.change.setObjectName("change")
        self.verticalLayout_2.addWidget(self.change)
        self.order_change = QtWidgets.QPushButton(self.layoutWidget2)
        self.order_change.setMinimumSize(QtCore.QSize(93, 29))
        self.order_change.setMaximumSize(QtCore.QSize(93, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.order_change.setFont(font)
        self.order_change.setStyleSheet("")
        self.order_change.setObjectName("order_change")
        self.verticalLayout_2.addWidget(self.order_change)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.addr = QtWidgets.QLabel(self.layoutWidget2)
        self.addr.setMinimumSize(QtCore.QSize(81, 30))
        self.addr.setMaximumSize(QtCore.QSize(81, 30))
        self.addr.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.addr.setObjectName("addr")
        self.horizontalLayout_6.addWidget(self.addr)
        self.show_addr = QtWidgets.QLabel(self.layoutWidget2)
        self.show_addr.setMinimumSize(QtCore.QSize(200, 30))
        self.show_addr.setMaximumSize(QtCore.QSize(200, 30))
        self.show_addr.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.show_addr.setText("")
        self.show_addr.setObjectName("show_addr")
        self.horizontalLayout_6.addWidget(self.show_addr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addr_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.addr_2.setMinimumSize(QtCore.QSize(81, 30))
        self.addr_2.setMaximumSize(QtCore.QSize(81, 30))
        self.addr_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.addr_2.setObjectName("addr_2")
        self.horizontalLayout_7.addWidget(self.addr_2)
        self.show_weather = QtWidgets.QLabel(self.layoutWidget2)
        self.show_weather.setMinimumSize(QtCore.QSize(200, 30))
        self.show_weather.setMaximumSize(QtCore.QSize(200, 30))
        self.show_weather.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.show_weather.setText("")
        self.show_weather.setObjectName("show_weather")
        self.horizontalLayout_7.addWidget(self.show_weather)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.refresh = QtWidgets.QPushButton(self.layoutWidget2)
        self.refresh.setMinimumSize(QtCore.QSize(91, 31))
        self.refresh.setMaximumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.refresh.setFont(font)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout_3.addWidget(self.refresh)
        self.postsql = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(98)
        sizePolicy.setVerticalStretch(31)
        sizePolicy.setHeightForWidth(self.postsql.sizePolicy().hasHeightForWidth())
        self.postsql.setSizePolicy(sizePolicy)
        self.postsql.setMinimumSize(QtCore.QSize(98, 31))
        self.postsql.setMaximumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.postsql.setFont(font)
        self.postsql.setObjectName("postsql")
        self.horizontalLayout_3.addWidget(self.postsql)
        self.yuyinzhushou = QtWidgets.QPushButton(self.layoutWidget2)
        self.yuyinzhushou.setMinimumSize(QtCore.QSize(88, 31))
        self.yuyinzhushou.setMaximumSize(QtCore.QSize(88, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.yuyinzhushou.setFont(font)
        self.yuyinzhushou.setStyleSheet("")
        self.yuyinzhushou.setCheckable(False)
        self.yuyinzhushou.setChecked(False)
        self.yuyinzhushou.setObjectName("yuyinzhushou")
        self.horizontalLayout_3.addWidget(self.yuyinzhushou)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.times = QtWidgets.QLabel(self.layoutWidget2)
        self.times.setMinimumSize(QtCore.QSize(81, 30))
        self.times.setMaximumSize(QtCore.QSize(81, 30))
        self.times.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color:rgb(243, 243, 243)")
        self.times.setObjectName("times")
        self.horizontalLayout_4.addWidget(self.times)
        self.show_time = QtWidgets.QLabel(self.layoutWidget2)
        self.show_time.setMinimumSize(QtCore.QSize(200, 30))
        self.show_time.setMaximumSize(QtCore.QSize(200, 30))
        self.show_time.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.show_time.setText("")
        self.show_time.setObjectName("show_time")
        self.horizontalLayout_4.addWidget(self.show_time)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleName.setText(_translate("Form", "智能窗帘系统 "))
        self.state_3.setText(_translate("Form", "查询数据 :"))
        self.years.setCurrentText(_translate("Form", "2018"))
        self.years.setItemText(0, _translate("Form", "2018"))
        self.years.setItemText(1, _translate("Form", "2019"))
        self.years.setItemText(2, _translate("Form", "2020"))
        self.times_4.setText(_translate("Form", "年"))
        self.months.setCurrentText(_translate("Form", "01"))
        self.months.setItemText(0, _translate("Form", "01"))
        self.months.setItemText(1, _translate("Form", "02"))
        self.months.setItemText(2, _translate("Form", "03"))
        self.months.setItemText(3, _translate("Form", "04"))
        self.months.setItemText(4, _translate("Form", "05"))
        self.months.setItemText(5, _translate("Form", "06"))
        self.months.setItemText(6, _translate("Form", "07"))
        self.months.setItemText(7, _translate("Form", "08"))
        self.months.setItemText(8, _translate("Form", "09"))
        self.months.setItemText(9, _translate("Form", "10"))
        self.months.setItemText(10, _translate("Form", "11"))
        self.months.setItemText(11, _translate("Form", "12"))
        self.times_2.setText(_translate("Form", "月"))
        self.days.setCurrentText(_translate("Form", "01"))
        self.days.setItemText(0, _translate("Form", "01"))
        self.days.setItemText(1, _translate("Form", "02"))
        self.days.setItemText(2, _translate("Form", "03"))
        self.days.setItemText(3, _translate("Form", "04"))
        self.days.setItemText(4, _translate("Form", "05"))
        self.days.setItemText(5, _translate("Form", "06"))
        self.days.setItemText(6, _translate("Form", "07"))
        self.days.setItemText(7, _translate("Form", "08"))
        self.days.setItemText(8, _translate("Form", "09"))
        self.days.setItemText(9, _translate("Form", "10"))
        self.days.setItemText(10, _translate("Form", "11"))
        self.days.setItemText(11, _translate("Form", "12"))
        self.days.setItemText(12, _translate("Form", "13"))
        self.days.setItemText(13, _translate("Form", "14"))
        self.days.setItemText(14, _translate("Form", "15"))
        self.days.setItemText(15, _translate("Form", "16"))
        self.days.setItemText(16, _translate("Form", "17"))
        self.days.setItemText(17, _translate("Form", "18"))
        self.days.setItemText(18, _translate("Form", "19"))
        self.days.setItemText(19, _translate("Form", "20"))
        self.days.setItemText(20, _translate("Form", "21"))
        self.days.setItemText(21, _translate("Form", "22"))
        self.days.setItemText(22, _translate("Form", "23"))
        self.days.setItemText(23, _translate("Form", "24"))
        self.days.setItemText(24, _translate("Form", "25"))
        self.days.setItemText(25, _translate("Form", "26"))
        self.days.setItemText(26, _translate("Form", "27"))
        self.days.setItemText(27, _translate("Form", "28"))
        self.days.setItemText(28, _translate("Form", "29"))
        self.days.setItemText(29, _translate("Form", "30"))
        self.days.setItemText(30, _translate("Form", "31"))
        self.times_3.setText(_translate("Form", "日"))
        self.Analysisbutton.setText(_translate("Form", "查询"))
        self.show_data.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.temp.setText(_translate("Form", "温度 :"))
        self.light.setText(_translate("Form", "光强 :"))
        self.state.setText(_translate("Form", "当前模式 :"))
        self.state_2.setText(_translate("Form", "当前状态 :"))
        self.show_temp.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.show_light.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.show_state.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.show_state_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SerialCOMLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">串口选择</span></p></body></html>"))
        self.SerialBaudRateLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">波特率</span></p></body></html>"))
        self.OpenLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">串口操作</span></p></body></html>"))
        self.temp_2.setText(_translate("Form", "操作模式 "))
        self.send_orders_2.setText(_translate("Form", "发送指令"))
        self.SerialBaudRateComboBox.setItemText(0, _translate("Form", "9600"))
        self.SerialBaudRateComboBox.setItemText(1, _translate("Form", "19200"))
        self.SerialBaudRateComboBox.setItemText(2, _translate("Form", "57600"))
        self.SerialBaudRateComboBox.setItemText(3, _translate("Form", "112500"))
        self.SerialBaudRateComboBox.setItemText(4, _translate("Form", "自定义"))
        self.OpenButton.setText(_translate("Form", "打开串口"))
        self.change.setText(_translate("Form", "手动"))
        self.order_change.setText(_translate("Form", "(打开/关闭)"))
        self.addr.setText(_translate("Form", "当前位置 :"))
        self.addr_2.setText(_translate("Form", "今天天气 :"))
        self.refresh.setText(_translate("Form", "刷新"))
        self.postsql.setText(_translate("Form", "插入当前数据"))
        self.yuyinzhushou.setText(_translate("Form", "语音助手"))
        self.times.setText(_translate("Form", "当前时间 :"))

